import { jsPDF } from 'jspdf';
import { Contract, Shop } from '@/types';
import { formatCurrency, formatDate } from './utils';

// Thai font is not supported by default in jsPDF
// We'll use basic characters and formatting

export interface ContractPDFData {
    contract: Contract;
    shop: Shop;
    landlordName?: string;
}

export function generateContractPDF(data: ContractPDFData): void {
    const { contract, shop, landlordName = 'ตลาดลานใจใหญ่' } = data;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('RENTAL CONTRACT', pageWidth / 2, y, { align: 'center' });
    doc.text('สัญญาเช่าร้านค้า', pageWidth / 2, y + 8, { align: 'center' });

    y += 25;

    // Contract Number
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Contract No: ${contract.contractNumber}`, pageWidth / 2, y, { align: 'center' });

    y += 20;

    // Horizontal line
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);

    y += 15;

    // Parties Section
    doc.setFont('helvetica', 'bold');
    doc.text('PARTIES:', margin, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.text(`Landlord: ${landlordName}`, margin, y);
    y += 8;
    doc.text(`Tenant: ${shop.ownerName}`, margin, y);
    y += 8;
    doc.text(`Shop: ${shop.name} (Stall #${shop.stallNumber})`, margin, y);
    y += 8;
    doc.text(`Phone: ${shop.phone}`, margin, y);

    y += 15;

    // Contract Details Section
    doc.setFont('helvetica', 'bold');
    doc.text('CONTRACT DETAILS:', margin, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.text(`Start Date: ${formatDate(contract.startDate)}`, margin, y);
    y += 8;
    doc.text(`End Date: ${formatDate(contract.endDate)}`, margin, y);
    y += 8;
    doc.text(`Monthly Rent: ${formatCurrency(contract.monthlyRent)}`, margin, y);
    y += 8;
    doc.text(`Deposit Amount: ${formatCurrency(contract.depositAmount)}`, margin, y);

    y += 15;

    // Terms Section
    if (contract.terms) {
        doc.setFont('helvetica', 'bold');
        doc.text('TERMS AND CONDITIONS:', margin, y);
        y += 10;

        doc.setFont('helvetica', 'normal');
        const splitTerms = doc.splitTextToSize(contract.terms, pageWidth - margin * 2);
        doc.text(splitTerms, margin, y);
        y += splitTerms.length * 6 + 10;
    }

    // Standard Terms
    y += 5;
    doc.setFont('helvetica', 'bold');
    doc.text('STANDARD TERMS:', margin, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    const standardTerms = [
        '1. The tenant agrees to pay rent on or before the 5th of each month.',
        '2. Utility costs (electricity and water) are separate and billed monthly.',
        '3. The tenant shall not sublet the premises without written consent.',
        '4. The landlord reserves the right to inspect the premises with notice.',
        '5. Deposit will be refunded upon contract end, subject to damage assessment.'
    ];

    standardTerms.forEach(term => {
        const splitTerm = doc.splitTextToSize(term, pageWidth - margin * 2);
        doc.text(splitTerm, margin, y);
        y += splitTerm.length * 6 + 3;
    });

    y += 20;

    // Signature Section
    const signatureY = Math.max(y, 220);

    doc.setFont('helvetica', 'bold');
    doc.text('SIGNATURES:', margin, signatureY);

    // Landlord Signature
    doc.setFont('helvetica', 'normal');
    doc.text('Landlord:', margin, signatureY + 15);
    doc.line(margin, signatureY + 30, margin + 60, signatureY + 30);
    doc.text(`(${landlordName})`, margin, signatureY + 38);

    // Tenant Signature
    doc.text('Tenant:', pageWidth - margin - 60, signatureY + 15);
    doc.line(pageWidth - margin - 60, signatureY + 30, pageWidth - margin, signatureY + 30);
    doc.text(`(${shop.ownerName})`, pageWidth - margin - 60, signatureY + 38);

    // Date
    doc.text(`Date: _________________`, pageWidth / 2 - 20, signatureY + 50);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Generated by Lanjaiyai Market Management System', pageWidth / 2, 285, { align: 'center' });

    // Download
    doc.save(`Contract_${contract.contractNumber}.pdf`);
}

// Generate Invoice PDF
export interface InvoicePDFData {
    invoiceNumber: string;
    shopName: string;
    ownerName: string;
    items: { description: string; amount: number }[];
    totalAmount: number;
    dueDate: string;
    createdAt: string;
}

export function generateInvoicePDF(data: InvoicePDFData): void {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('INVOICE', pageWidth / 2, y, { align: 'center' });
    doc.text('ใบแจ้งหนี้', pageWidth / 2, y + 8, { align: 'center' });

    y += 25;

    // Invoice Info
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Invoice No: ${data.invoiceNumber}`, margin, y);
    doc.text(`Date: ${formatDate(data.createdAt)}`, pageWidth - margin - 50, y);

    y += 20;

    // Customer Info
    doc.setFont('helvetica', 'bold');
    doc.text('BILL TO:', margin, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.text(data.shopName, margin, y);
    y += 8;
    doc.text(data.ownerName, margin, y);

    y += 20;

    // Items Table Header
    doc.setFont('helvetica', 'bold');
    doc.text('Description', margin, y);
    doc.text('Amount', pageWidth - margin - 30, y);

    y += 5;
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Items
    doc.setFont('helvetica', 'normal');
    data.items.forEach(item => {
        doc.text(item.description, margin, y);
        doc.text(formatCurrency(item.amount), pageWidth - margin - 30, y);
        y += 10;
    });

    // Total
    y += 5;
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL', margin, y);
    doc.text(formatCurrency(data.totalAmount), pageWidth - margin - 30, y);

    y += 20;

    // Due Date
    doc.setFont('helvetica', 'normal');
    doc.text(`Due Date: ${formatDate(data.dueDate)}`, margin, y);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Lanjaiyai Market - Thank you for your business!', pageWidth / 2, 285, { align: 'center' });

    doc.save(`Invoice_${data.invoiceNumber}.pdf`);
}
